apiVersion: v1
kind: Service
metadata:
  name: angular-demo
  labels:
    run: angular-demo
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: angular-demo
  sessionAffinity: None
  type: LoadBalancer
